### DISCUSSION TITLE
Don't add extra spaces (x2) when encrypt

### DISCUSSION THREAD

**Discussion by anutator** [FiloSottile/age#506] [General]
When I encrypt yaml file I get 4 spaces instead of 2 spaces and 8 spaces instead of 4 spaces. I'd like to work as before encrypting.
sops 3.7.3, Age 1.1.1, Linux (Ubuntu), vim editor. Is it problem of SOPS or age? Example:

Original

```yml
secretEnv:
  MAILER_DSN: mypass1

secretTiers:
  DIRECTUM_SOAP_SERVER_PASSWORD:
    _default: passexample1
    prod: passexample2
...
```

After encryption

```yml
secretEnv:
    MAILER_DSN: ENC[AES256_GCM,data:e2WdQdBlQoDxJ43iBOVTWrwun/AY6IwbGTA1aUH6HUbXFGzVnPb3W6GtytGaEJUZPJZb6E1lUyjE7ktWo6+MFA==,iv:Xh8PkXBCjA2Owr+2/lWt33MdHA5c8xWKyqaLOZKTTDo=,tag:hRJKsZQf3fxuO1NmsfE5Rw==,type:str]

secretTiers:

    DIRECTUM_SOAP_SERVER_PASSWORD:
        _default: ENC[AES256_GCM,data:YvgYrRbhlJZ1308=,iv:fTL4VejN5nlwtsdvvSIREpWg6vkmrZSSeoVKWgsQibuAk=,tag:+eYqTEOYIOrNrcf35vaN1w==,type:str]
        prod: ENC[AES256_GCM,data:Zuk8AldzNSoJ,iv:w1AbOW2yPxdvTbxT517FynJ9khTNv8T4lkq2LBXeedE=,tag:yJ9i7x1PjMVUeKAPb0ZU7A==,type:str]
```
